# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([[10, 11, 12],
                 [13, 14, 15]])

print(arrA)

[[10 11 12]
 [13 14 15]]


In [3]:
for x in arrA:
    print(x * 2)

[20 22 24]
[26 28 30]


In [4]:
for x in arrA:
    for y in x:
        print(y * 2)

20
22
24
26
28
30


The first loop works with entire rows of the array at once, so each row is multiplied by 2 together.
The second loop goes through each individual number inside the rows and multiplies each value separately.

In [5]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# This result is different because x represents the whole row,
# so x * 2 multiplies the entire row each time instead of one value.

[20 22 24]
[20 22 24]
[20 22 24]
[26 28 30]
[26 28 30]
[26 28 30]


## Joining and Stacking Arrays

In [6]:
joined_array_1 = np.concatenate((arrA, arrA))

print(joined_array_1)

[[10 11 12]
 [13 14 15]
 [10 11 12]
 [13 14 15]]


In [7]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)

print(joined_array_2)

[[10 11 12 10 11 12]
 [13 14 15 13 14 15]]


In [8]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))

print(stacked_array_1)

[[[10 11 12]
  [13 14 15]
  [10 11 12]
  [13 14 15]]

 [[10 11 12]
  [13 14 15]
  [10 11 12]
  [13 14 15]]]


In [12]:
print(joined_array_1.shape)
print(joined_array_2.shape)

# Reshape joined_array_2 so it matches joined_array_1
joined_array_2 = joined_array_2.reshape(4, 3)

# Stack the arrays
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

# Print result
print(stacked_array_2)

(4, 3)
(2, 6)
[[[10 11 12]
  [13 14 15]
  [10 11 12]
  [13 14 15]]

 [[10 11 12]
  [10 11 12]
  [13 14 15]
  [13 14 15]]]


In [13]:
another_joined_array = np.concatenate((joined_array_1, arrA))

print(another_joined_array)

[[10 11 12]
 [13 14 15]
 [10 11 12]
 [13 14 15]
 [10 11 12]
 [13 14 15]]


In [15]:
horizontal_stack = np.hstack((arrA, arrA))
# hstack joins arrays side by side horizontally

vertical_stack = np.vstack((arrA, arrA))
# vstack joins arrays vertically by rows

depth_stack = np.dstack((arrA, arrA))
# dstack joins arrays along a third depth dimension

print(horizontal_stack)
print(vertical_stack)
print(depth_stack)

[[10 11 12 10 11 12]
 [13 14 15 13 14 15]]
[[10 11 12]
 [13 14 15]
 [10 11 12]
 [13 14 15]]
[[[10 10]
  [11 11]
  [12 12]]

 [[13 13]
  [14 14]
  [15 15]]]


## Splitting Arrays

In [16]:
splitsky = np.array_split(joined_array_1, 2)

print(splitsky)

# Result:
# 2 arrays are created.
# Each array is still two-dimensional.

[array([[10, 11, 12],
       [13, 14, 15]]), array([[10, 11, 12],
       [13, 14, 15]])]


In [17]:
spliterino = np.array_split(joined_array_1, 3)

print(spliterino)

# Result:
# 3 arrays are created.
# Each array is still two-dimensional,
# but the arrays may not all contain the same number of rows.

[array([[10, 11, 12],
       [13, 14, 15]]), array([[10, 11, 12]]), array([[13, 14, 15]])]


## Searching and Replacing Array Values

In [18]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')

print(result_1)

[['10' 'odd' '12']
 ['odd' '14' 'odd']]


## Sorting and Filtering Arrays

In [19]:
arrB = np.array([[7, 6],
                 [13, 5],
                 [7, 3]])

arrB_sorted = np.sort(arrB)

print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [20]:
print(arrB)

z = arrB < 7

arrC = arrB[z]

print(arrC)

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [21]:
y = arrB >= 7

arrD = arrB[y]

print(arrD)

[ 7 13  7]
