# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

In [2]:
r_1 = np.random.randint(1, 21, size=2)

print(r_1)

[ 1 18]


In [3]:
r_2 = np.random.randint(1, 21, size=(1, 2))

print(r_2)

[[20 15]]


In [4]:
r_3 = np.random.rand(2, 1)

print(r_3)

[[0.2348408 ]
 [0.34367869]]


In [5]:
r_4 = np.random.randint(20, 101, size=(4, 5))

print(r_4)

[[66 55 23 28 82]
 [54 62 35 23 90]
 [24 33 24 81 91]
 [67 68 46 33 51]]


In [6]:
r_5 = np.random.rand(4, 5)

print(r_5)

[[0.71444399 0.55320568 0.90022259 0.3151997  0.1316948 ]
 [0.24526682 0.18318213 0.73325969 0.19785667 0.45838871]
 [0.35767132 0.51909303 0.4830203  0.95946146 0.45515331]
 [0.79716168 0.61756397 0.46722823 0.9944993  0.89301368]]


## Generating Random Choices from an Array

In [7]:
students = np.array([
    "Nahom", "Daniel", "Lesley", "Jordan",
    "Naomi", "Danait", "Ahmad", "Lula",
    "Ruth", "Peniel", "Chris", "Dinu"
])

print(students)

['Nahom' 'Daniel' 'Lesley' 'Jordan' 'Naomi' 'Danait' 'Ahmad' 'Lula' 'Ruth'
 'Peniel' 'Chris' 'Dinu']


In [8]:
call_on = np.random.choice(students)

print(call_on)

Jordan


In [9]:
breakout_groups = np.random.choice(students, size=(3, 4))

print(breakout_groups)

# This is not the best way to assign breakout groups
# because some students may appear more than once
# while others may not appear at all.

[['Ruth' 'Daniel' 'Ahmad' 'Danait']
 ['Lula' 'Jordan' 'Ruth' 'Peniel']
 ['Ahmad' 'Ahmad' 'Jordan' 'Lesley']]


In [10]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.10, 0.05, 0.10,
       0.05, 0.05, 0.10, 0.05,
       0.05, 0.05, 0.10, 0.00]
)

print(call_on_weighted)

# Probability explanation:
# John has a 30% chance of being selected.
# Mia has a 0% chance of being selected.
# Other students have smaller probabilitie

['Nahom' 'Nahom' 'Daniel' 'Nahom' 'Nahom']


## Generating a Normal Distribution

In [11]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

print(bell_curve)

[[ 4.23728759  8.31529514 17.49406083  5.68519091 16.25746175]
 [ 2.88506523 12.06354438 10.51722637  6.97795665 12.30712075]
 [10.63432094 17.72155219  6.69669715  8.88838944 13.3998224 ]
 [ 6.21860405 11.76762008 11.39808113 11.01033141  2.16222447]]
