# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [2]:
# Random sample arrays

r_1 = np.random.rand(5)

r_2 = np.random.randint(1, 20, size=5)

r_3 = np.random.randn(4, 4)

r_4 = np.random.randint(1, 50, size=10)

r_5 = np.random.choice([10, 20, 30, 40, 50], size=6)

# Print arrays
print("r_1:\n", r_1)
print("\nr_2:\n", r_2)
print("\nr_3:\n", r_3)
print("\nr_4:\n", r_4)
print("\nr_5:\n", r_5)

r_1:
 [0.1180721  0.26696933 0.43517716 0.38051987 0.87865162]

r_2:
 [ 6  4 19  8 11]

r_3:
 [[ 2.11676558 -1.72752939  0.4232763  -0.890667  ]
 [-1.20111409  0.16404218  0.65275795 -0.58786569]
 [-1.21020861  0.18355002 -1.36068345  0.853577  ]
 [ 0.65639425 -0.58190241 -0.46925302  1.22331872]]

r_4:
 [ 9 18  5 38 21 22  4  5 40 34]

r_5:
 [40 40 30 50 20 50]


## Permutations

In [3]:
print("Original r_4:")
print(r_4)

Original r_4:
[ 9 18  5 38 21 22  4  5 40 34]


In [4]:
np.random.shuffle(r_4)

print("Shuffled r_4:")
print(r_4)

Shuffled r_4:
[ 4 18  5  5  9 34 40 22 38 21]


The elements in the array were rearranged into a random order.
The shuffle operation changed the original array directly instead of creating a new array.

In [5]:
new_shuffle = np.random.permutation(r_4)

print("new_shuffle:")
print(new_shuffle)

print("\nr_4 after permutation:")
print(r_4)

new_shuffle:
[ 9 21 18 38  4 22  5  5 40 34]

r_4 after permutation:
[ 4 18  5  5  9 34 40 22 38 21]


`shuffle` changes the original array directly by rearranging its elements.

`permutation` creates a new shuffled version of the array while keeping the original array unchanged.

Use `shuffle` when you want to permanently randomize an array.
Use `permutation` when you want a shuffled copy without modifying the original data.

## Mathematical Operations

In [6]:
print("r_1:")
print(r_1)
print("Shape of r_1:", r_1.shape)

print("\nr_2:")
print(r_2)
print("Shape of r_2:", r_2.shape)

result_1 = np.add(r_1, r_2)

print("\nr_1 + r_2:")
print(result_1)
print("Shape of result:", result_1.shape)

r_1:
[0.1180721  0.26696933 0.43517716 0.38051987 0.87865162]
Shape of r_1: (5,)

r_2:
[ 6  4 19  8 11]
Shape of r_2: (5,)

r_1 + r_2:
[ 6.1180721   4.26696933 19.43517716  8.38051987 11.87865162]
Shape of result: (5,)


In [8]:
print("r_1:")
print(r_1)
print("Shape of r_1:", r_1.shape)

print("\nr_3:")
print(r_3)
print("Shape of r_3:", r_3.shape)

try:
    result_2 = np.add(r_1, r_3)

    print("\nr_1 + r_3:")
    print(result_2)
    print("Shape of result:", result_2.shape)

except ValueError as e:
    print("\nError:")
    print(e)

# The arrays cannot be added because their shapes are incompatible for broadcasting.

r_1:
[0.1180721  0.26696933 0.43517716 0.38051987 0.87865162]
Shape of r_1: (5,)

r_3:
[[ 2.11676558 -1.72752939  0.4232763  -0.890667  ]
 [-1.20111409  0.16404218  0.65275795 -0.58786569]
 [-1.21020861  0.18355002 -1.36068345  0.853577  ]
 [ 0.65639425 -0.58190241 -0.46925302  1.22331872]]
Shape of r_3: (4, 4)

Error:
operands could not be broadcast together with shapes (5,) (4,4) 


In [10]:
print("r_2:")
print(r_2)
print("Shape of r_2:", r_2.shape)

print("\nr_4:")
print(r_4)
print("Shape of r_4:", r_4.shape)

try:
    result_3 = np.add(r_2, r_4)

    print("\nr_2 + r_4:")
    print(result_3)
    print("Shape of result:", result_3.shape)

except ValueError as e:
    print("\nError:")
    print(e)

# The arrays cannot be added because their shapes are incompatible.
# Arrays with shapes (5,) and (10,) cannot be broadcast together.

r_2:
[ 6  4 19  8 11]
Shape of r_2: (5,)

r_4:
[ 4 18  5  5  9 34 40 22 38 21]
Shape of r_4: (10,)

Error:
operands could not be broadcast together with shapes (5,) (10,) 


In [12]:
# r_1 + r_4
try:
    print("r_1 + r_4:")
    print(np.add(r_1, r_4))

except ValueError as e:
    print("Error for r_1 + r_4:")
    print(e)

print("\n------------------\n")

# r_2 + r_4
try:
    print("r_2 + r_4:")
    print(np.add(r_2, r_4))

except ValueError as e:
    print("Error for r_2 + r_4:")
    print(e)

print("\n------------------\n")

# r_3 + r_4
try:
    print("r_3 + r_4:")
    print(np.add(r_3, r_4))

except ValueError as e:
    print("Error for r_3 + r_4:")
    print(e)

# Findings:
# Arrays with incompatible shapes cannot be broadcast together.
# NumPy raises a ValueError when shapes do not match broadcasting rules

r_1 + r_4:
Error for r_1 + r_4:
operands could not be broadcast together with shapes (5,) (10,) 

------------------

r_2 + r_4:
Error for r_2 + r_4:
operands could not be broadcast together with shapes (5,) (10,) 

------------------

r_3 + r_4:
Error for r_3 + r_4:
operands could not be broadcast together with shapes (4,4) (10,) 


In [13]:
print(r_4)

print("\nr_4 + np.array([1]):")
print(np.add(r_4, np.array([1])))

[ 4 18  5  5  9 34 40 22 38 21]

r_4 + np.array([1]):
[ 5 19  6  6 10 35 41 23 39 22]


In [14]:
print(r_4)

print("\nr_4 + np.array([[1]]):")
print(np.add(r_4, np.array([[1]])))

[ 4 18  5  5  9 34 40 22 38 21]

r_4 + np.array([[1]]):
[[ 5 19  6  6 10 35 41 23 39 22]]


In [16]:
print(r_4)

print("\nr_4 + np.array([1,1,1,1,1]):")

try:
    print(np.add(r_4, np.array([1,1,1,1,1])))

except ValueError as e:
    print("Error:")
    print(e)

# The arrays cannot be broadcast together because
# their shapes (10,) and (5,) are incompatible.

[ 4 18  5  5  9 34 40 22 38 21]

r_4 + np.array([1,1,1,1,1]):
Error:
operands could not be broadcast together with shapes (10,) (5,) 


In [17]:
print(r_4)

print("\nr_4 + np.array([[1],[1]]):")
print(np.add(r_4, np.array([[1],[1]])))

# Error finding:
# This produces a broadcasting error because the shapes are incompatible.

[ 4 18  5  5  9 34 40 22 38 21]

r_4 + np.array([[1],[1]]):
[[ 5 19  6  6 10 35 41 23 39 22]
 [ 5 19  6  6 10 35 41 23 39 22]]


Broadcasting allows NumPy to perform operations on arrays with different shapes
when their dimensions are compatible.

When using the add function, NumPy matches elements by position. If one array
has fewer dimensions or contains a single value, NumPy automatically stretches
(or broadcasts) that value across the larger array.

The shape of the resulting array depends on the compatible dimensions of the
arrays being combined.

## Rounding

In [18]:
print("r_3:")
print(r_3)

r_3:
[[ 2.11676558 -1.72752939  0.4232763  -0.890667  ]
 [-1.20111409  0.16404218  0.65275795 -0.58786569]
 [-1.21020861  0.18355002 -1.36068345  0.853577  ]
 [ 0.65639425 -0.58190241 -0.46925302  1.22331872]]


In [19]:
print("Using trunc:")
print(np.trunc(r_3))

Using trunc:
[[ 2. -1.  0. -0.]
 [-1.  0.  0. -0.]
 [-1.  0. -1.  0.]
 [ 0. -0. -0.  1.]]


In [20]:
print("Using fix:")
print(np.fix(r_3))

Using fix:
[[ 2. -1.  0. -0.]
 [-1.  0.  0. -0.]
 [-1.  0. -1.  0.]
 [ 0. -0. -0.  1.]]


In [21]:
print("Using floor:")
print(np.floor(r_3))

Using floor:
[[ 2. -2.  0. -1.]
 [-2.  0.  0. -1.]
 [-2.  0. -2.  0.]
 [ 0. -1. -1.  1.]]


In [22]:
print("Using ceil:")
print(np.ceil(r_3))

Using ceil:
[[ 3. -1.  1. -0.]
 [-1.  1.  1. -0.]
 [-1.  1. -1.  1.]
 [ 1. -0. -0.  2.]]


In [23]:
print("Rounded to 2 decimal places:")
print(np.round(r_3, 2))

Rounded to 2 decimal places:
[[ 2.12 -1.73  0.42 -0.89]
 [-1.2   0.16  0.65 -0.59]
 [-1.21  0.18 -1.36  0.85]
 [ 0.66 -0.58 -0.47  1.22]]


## Cumulative Operations

In [24]:
print("r_4:")
print(r_4)

r_4:
[ 4 18  5  5  9 34 40 22 38 21]


In [25]:
print("Sum of all values in r_4:")
print(np.sum(r_4))

Sum of all values in r_4:
196


In [26]:
print("Sum along axis 0:")
print(np.sum(r_4, axis=0))

Sum along axis 0:
196


In [27]:
try:
    print("Sum along axis 1:")
    print(np.sum(r_4, axis=1))

except ValueError as e:
    print("Error:")
    print(e)

except Exception as e:
    print("Error:")
    print(e)

# r_4 is a one-dimensional array, so axis 1 does not exist.

Sum along axis 1:
Error:
axis 1 is out of bounds for array of dimension 1


In [28]:
print("Cumulative sum of r_4:")
print(np.cumsum(r_4))

Cumulative sum of r_4:
[  4  22  27  32  41  75 115 137 175 196]


In [29]:
print("Cumulative sum along axis 0:")
print(np.cumsum(r_4, axis=0))

Cumulative sum along axis 0:
[  4  22  27  32  41  75 115 137 175 196]


## Grocery Problem

In [30]:
# Categories:
# [vegetables, fruits, snacks, beverages]

bag1 = np.array([2, 3, 4, 0])

bag2 = np.array([4, 0, 1, 2])

print("bag1:")
print(bag1)

print("\nbag2:")
print(bag2)

bag1:
[2 3 4 0]

bag2:
[4 0 1 2]


In [31]:
bag1_total = np.sum(bag1)
bag2_total = np.sum(bag2)

print(f"The first bag contains {bag1_total} items, and the second bag contains {bag2_total} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [32]:
totals = np.add(bag1, bag2)

vegetables = totals[0]
fruits = totals[1]
snacks = totals[2]
beverages = totals[3]

print(f"There are {vegetables} vegetables, {fruits} fruits, {snacks} boxes of snacks, and {beverages} beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [33]:
# Ali's door knocks from Monday to Friday
ali = np.array([5, 4, 6, 4, 2])

print("Ali:")
print(ali)

Ali:
[5 4 6 4 2]


In [34]:
# Ben missed Monday
ben = np.array([0, 5, 5, 3, 4])

print("Ben:")
print(ben)

Ben:
[0 5 5 3 4]


In [35]:
# Carla missed Wednesday
carla = np.array([3, 6, 0, 3, 4])

print("Carla:")
print(carla)

Carla:
[3 6 0 3 4]


In [36]:
all_knocks = np.array([ali, ben, carla])

print("All knocks:")
print(all_knocks)

All knocks:
[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [37]:
# Total for each person
ali_total = np.sum(ali)
ben_total = np.sum(ben)
carla_total = np.sum(carla)

# Group total
group_total = np.sum(all_knocks)

print(f"Ali knocked on {ali_total} doors.")
print(f"Ben knocked on {ben_total} doors.")
print(f"Carla knocked on {carla_total} doors.")

print(f"\nThe group collectively knocked on {group_total} doors.")

Ali knocked on 21 doors.
Ben knocked on 17 doors.
Carla knocked on 16 doors.

The group collectively knocked on 54 doors.


In [38]:
# Total knocks per day
daily_totals = np.sum(all_knocks, axis=0)

print("Daily totals:")
print(daily_totals)

# Rolling total of knocks
rolling_knocks = np.cumsum(daily_totals)

print("\nRolling total of knocks:")
print(rolling_knocks)

# Estimated votes (1 vote for every 2 knocks)
estimated_votes = rolling_knocks * 0.5

print("\nRolling estimated votes:")
print(estimated_votes)

Daily totals:
[ 8 15 11 10 10]

Rolling total of knocks:
[ 8 23 34 44 54]

Rolling estimated votes:
[ 4.  11.5 17.  22.  27. ]
